### ISSUE TITLE
go to Harmony doesn't filter out URL queries

### ISSUE THREAD

**Issue by UltimateRiff** [RustyNova016/MusicBrainz-UserScripts#18]
see https://github.com/kellnerd/harmony/issues/100 for details

**Comment by RustyNova016** [comment]
Didn't I already fixed that one? In #14 ?
Maybe try updating/readding the userscript?

**Comment by UltimateRiff** [comment]
just removed, re-added, closed and reopened my browser, and still getting the query, same as before (in harmony#100)
